import Head from "next/head";
import Link from "next/link";
import { useEffect } from "react";

import { api } from "~/utils/api";

export default function Home() {
  const { isLoading, data } = api.post.getAll.useQuery();
  console.log(data);
  return (
    <>
      <Head>
        <title>X</title>
        <meta name="Twitter (X) clone" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="px-y-24 flex w-full flex-col px-4 py-2 sm:max-w-xl">
        <form action="" className="flex">
          <input
            type="text"
            className="w-full rounded-md bg-stone-800 px-4 py-1 outline-none"
          />
        </form>
        <div className="mt-4 flex flex-col gap-2">
          {data?.map((ele) => {
            return (
              <span
                className="rounded-md border border-dotted border-stone-700 p-2"
                key={ele.author}
              >
                {ele.post}
              </span>
            );
          })}
        </div>
      </main>
    </>
  );
}
